<?php

/**
 * @file
 * Exposes userpoints collect functionality via a service.
 */


/**
 * Implements hook_services_resources().
 */
function userpoints_collect_service_services_resources() {
  return array(
    'userpoints_collect' => array(
      'retrieve' => array(
        'help' => 'Retrieve points',
        'file' => array('file' => 'inc', 'module' => 'userpoints_collect_service', 'name' => 'resources/userpoints_collect_resource'),
        'callback' => '_userpoints_collect_resource_retrieve',
        'access callback' => '_userpoints_collect_resource_access',
        'access arguments' => array('retrieve'),
        'access arguments append' => TRUE,
        'args' => array(
          array(
            'name' => 'uid',
            'description' => 'The User ID.',
            'type' => 'int',
            'source' => array('path' => 0),
          ),
        ),
      ),
      'actions' => array(
        'eligibility' => array(
          'help' => 'Check the eligibility of an account to collect a point.',
          'file' => array('file' => 'inc', 'module' => 'userpoints_collect_service', 'name' => 'resources/userpoints_collect_resource'),
          'callback' => '_userpoints_collect_resource_eligibility',
          'access callback' => '_userpoints_collect_resource_access',
          'access arguments' => array('eligibility'),
          'access arguments append' => TRUE,
          'args' => array(),
        ),
        'add' => array(
          'help' => 'Add points to account if eligible.',
          'file' => array('file' => 'inc', 'module' => 'userpoints_collect_service', 'name' => 'resources/userpoints_collect_resource'),
          'callback' => '_userpoints_collect_resource_add',
          'access callback' => '_userpoints_collect_resource_access',
          'access arguments' => array('add'),
          'access arguments append' => TRUE,
          'args' => array(
            array(
              'name' => 'data',
              'description' => 'A userpoints object.',
              'type' => 'array',
              'optional' => TRUE,
              'source' => 'data',
            ),
          ),
        ),
        'get' => array(
          'help' => 'Add points to account if eligible.',
          'file' => array('file' => 'inc', 'module' => 'userpoints_collect_service', 'name' => 'resources/userpoints_collect_resource'),
          'callback' => '_userpoints_collect_resource_get',
          'access callback' => '_userpoints_collect_resource_access',
          'access arguments' => array('get'),
          'access arguments append' => TRUE,
          'args' => array(
            array(
              'name' => 'tid',
              'description' => 'The Category ID.',
              'type' => 'int',
              'source' => array('path' => 0),
            ),
          ),
        ),
      ),
    ),
  );
}
